###
#
# Get Charts
#
GET http://localhost:4004/chart/Chart
Authorization: Basic admin
Content-Type: application/json
{

}

###
#
# Add Chart
#
POST http://localhost:4004/chart/Chart
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{
    "id" : 99,
    "ticker" : "XMR",
    "type" : "close"
}

###
#
# Update Chart
#

PATCH http://localhost:4004/chart/Chart/1
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{
    "ticker" : "BTC",
    "type" : "adj_close"
}

###
#
# Fucked up query
#

GET http://localhost:4004/catalog/BTC?$filter=(year(date) gte 2023 and month(date) gte 4 and day(date) gte 1) and ( year(date) lte 2023 and month(date) lte 4 and (day) lte 19 )




####
#
#

POST http://localhost:4004/endpoint/RefreshData/
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{
    "ticker" : "BTC"
}



###
#
#


DELETE  http://localhost:4004/catalog/Crypto/00149bbd-3438-4916-8076-b17624b0c0eb
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true


###
#
#

POST http://localhost:4004/catalog/Crypto
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{"date":"2018-10-13","open":100.678001,"high":102.987999,"low":100.678001,"close":102.137001,"adj_close":102.137001,"volume":12537800,"ticker":"XMR","type":"real"}


###
#   Test action
#
POST http://localhost:4004/Catalog/DeleteTicker
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{
    "ticker" : "USDT"
}

###
#   Test command
#

POST http://localhost:4004/catalog/AddTicker
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{
    "ticker" : "XMR"
}

###
#   Test command
#

POST http://localhost:4004/endpoint/DeleteResult
Authorization: Basic admin
Content-Type: application/json;IEEE754Compatible=true

{

}
