= This documentation provides information about the datastructure currently used

== Current

At the moment we have several cryptocurrencies' historical data for one year, with fields including open, close, high, low.
We have separate entites for them regardless that the fields used are exactly the same.

=== Questions & notes

* Is there a way to put them into one service using parameters?


== One service strategy

The one service strategy says that as the key (date) is consistent throughout the csv files, we can change the column names and put every data in one big file, and we can access them more easily.

== Computed fields for analysis

While we have raw data, it may not be the best if we want to apply more complex analyis for the user to enjoy


== Experimental dataset

* In this dataset, we modify the csv (, and the service), where the date acts as a key, and with an underscore, every datatype is used in a single service
* This enables us to have multiple lines in a <LineChart /> comnponent
* This approach can be used as making joins on the date section of the records
* With every record in one dataset we can display multiple lines in one chart, which may or may not give a good representation of value, as the scale of these currencies can ultimately vary
* Defining how and what the used could display is another programmatic challange we'll yet to face.