= Data source

This doc details how the data is sourced.

== Current

Currently we download the historical data from selected cryptocurrencies from https://finance.yahoo.com, change the column names,change the commas to semicolons and rename the tables.

NOTE: The tables must be named as [namespace].[entity].csv

== Automation

As the download link for the csv files are easily understandable, we can edit them, and without much hassle, download more / different data using a script.
The hypotethical process would be something like this:
+
. The user gives us the 3 letter code for the cryptocurrency 
. We edit the base url, and download the csv file to `sample data values` or some other folder
. We change the column names
. We change the commas to semicolons
. We change the file name by the naming convention
. We create a `cds` entity in the `data_model` namespace, we can generate this file too with a template
. We add the selector to the json data storing the different selections
+
NOTE: This technique assumes that we have modular React components and the frontend as well as the backend refreshes when the files were modified.