= Bevezetés

== Témaválasztás indoklása

A mai világban minden nap találkozhatunk kriptovalutákkal különböző szentimentalitású hírekben. Szembünkbe tűnhetnek dollármilliárdos csalások, átverések de néha megjelennek az interjúk emberekkel akik hatalmas vagyonra tettek szert mert 10-15 éve vásároltak fillérekért egy teljesen ismeretlen kriptovalutát ami mai napra többet ér mint az arany. Az átlag ember nem tudja nyomon követni, hogy melyik kripto mennyit ér a millió közül, a legtöbb pénzügyi weboldal pedig túlságosan sok felesleges információt nyújt. 

== Megoldandó feladat

A probléma hogy az ingyenesen elérhető felületek nagyrésze túl sok információt nyújt a felhasználónak, vagy nem a megfelelő információkat prezentálja, hogy letisztult átfogó képet nyerjen a valuta jelenlegi állapotáról. Célunk hogy egy egyszerűen használható felületet biztosítsunk a felhasználó részére mely különböző kriptovaluták mozgásának követését, és összehasonlítását teszi lehetővé egy webes felületen keresztül, melyen csak azok az információk jelennek meg melyekre a felhasználó kíváncsi.

